;;; rom.asm - Safe unlocking program
;;
;; The program requires the user to enter a 4 digit PIN code by
;; setting the switches to the appropriate digit and then pressing
;; the center key to confirm the digit. Once completed, LED 0 or
;; 1 is set to display whether the user entered the correct
;; code (0702) or not.
;;
;; The program progresses linearlly up until the test for whether
;; the first digit (A) was correct. At this point, it branches into
;; one of two possibilities: either A was correct or incorrect. The
;; parallel branches then continue to test digits B, C, and D in the
;; same manner. At each point, the correct branch may transition to
;; the incorrect branch if the user enters the wrong digit, but not
;; vice versa:
;;
;;  Correct Incorrect
;;     A
;;     |\
;;     | \
;;     |  \
;;     |   \
;;     |    \
;;     A     A
;;     |\    |
;;     B \   |
;;     |  \  |
;;     |   \ |
;;     |    \|
;;     B     B
;;     |     |
;;       ...
;;
;; Generated by http://chriscummins.cc/disassembler and hand-annotated
;; with explanatory comments and better label names.

reset:
        seto 0x00, 0x00, 0x00   ; Clear all outputs
start:
        tsti 0x01, 0x20, 0x00   ; Centre button toggled
        bic start
        tsti 0x00, 0xF0, 0x00   ; All switches off
        bic a-correct
        buc a-incorrect

;; Correct digits
a-correct:
        seto 0x00, 0xFF, 0x80   ; Toggle LED 8
a-correct-confirm:
        tsti 0x01, 0x20, 0x20   ; Centre button toggled
        bic a-correct-confirm
a-correct-release:
        tsti 0x01, 0x20, 0x20   ; Centre button toggled
        bic a-correct-release
        tsti 0x00, 0xF0, 0x70   ; Only switch 7 on
        bic b-correct
        buc b-incorrect
b-correct:
        seto 0x00, 0xFF, 0x40   ; Toggle LED 7
b-correct-confirm:
        tsti 0x01, 0x20, 0x20   ; Centre button toggled
        bic b-correct-confirm
b-correct-release:
        tsti 0x01, 0x20, 0x20   ; Centre button toggled
        bic b-correct-release
        tsti 0x00, 0xF0, 0x00   ; All switches off
        bic c-correct
        buc c-incorrect
c-correct:
        seto 0x00, 0xFF, 0x20   ; Toggle LED 6
c-correct-confirm:
        tsti 0x01, 0x20, 0x20   ; Centre button toggled
        bic c-correct-confirm
c-correct-release:
        tsti 0x01, 0x20, 0x20   ; Centre button toggled
        bic c-correct-release
        tsti 0x00, 0xF0, 0x20   ; Only switch 2
        bic d-correct
        buc d-incorrect
d-correct:
        seto 0x00, 0xFF, 0x10   ; Toggle LED 5
d-correct-confirm:
        tsti 0x01, 0x20, 0x20   ; Centre button toggled
        bic d-correct-confirm
        seto 0x00, 0xFF, 0x01   ; Toggle LED 0
        buc code-correct

;; Incorrect digits. We don't actually need to test the switch inputs since we
;; know the code is incorrect.
a-incorrect:
        seto 0x00, 0xFF, 0x80   ; Toggle LED 8
a-incorrect-confirm:
        tsti 0x01, 0x20, 0x20   ; Centre button toggled
        bic a-incorrect-confirm
a-incorrect-release:
        tsti 0x01, 0x20, 0x20   ; Centre button toggled
        bic a-incorrect-release
b-incorrect:
        seto 0x00, 0xFF, 0x40   ; Toggle LED 7
b-incorrect-confirm:
        tsti 0x01, 0x20, 0x20   ; Centre button toggled
        bic b-incorrect-confirm
b-incorrect-release:
        tsti 0x01, 0x20, 0x20   ; Centre button toggled
        bic b-incorrect-release
c-incorrect:
        seto 0x00, 0xFF, 0x20   ; Toggle LED 6
c-incorrect-confirm:
        tsti 0x01, 0x20, 0x20   ; Centre button toggled
        bic c-incorrect-confirm
c-incorrect-release:
        tsti 0x01, 0x20, 0x20   ; Centre button toggled
        bic c-incorrect-release
d-incorrect:
        seto 0x00, 0xFF, 0x10   ; Toggle LED 5
d-incorrect-confirm:
        tsti 0x01, 0x20, 0x20   ; Centre button toggled
        bic d-incorrect-confirm
        seto 0x00, 0xFF, 0x02   ; Toggle LED 1
code-correct:
        tsti 0x01, 0x40, 0x00   ; Down button pressed
        bic code-correct
end:
        tsti 0x01, 0x40, 0x40   ; Down button toggled
        bic end
        buc reset               ; Repeat
        iuc
        iuc
        iuc
        iuc
        iuc

;; End of program code
